/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performanceTasks;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.text.*;

/**
 *
 * @author ihub9
 */
public class pt_simplepayrollsystem extends javax.swing.JFrame {

    /**
     * Creates new form pt_simplepayrollsystem
     */
    
    public pt_simplepayrollsystem() {
        // initilize compo
        initComponents();
        hour();
        ratefor();
    }
    
    // Change the "hourWork" field into 0.0 and add hr to the front. this cannot be change by the user
    private void hour()
    {
        NumberFormat format = new DecimalFormat("0.00' hr'");
        NumberFormatter decimalFormatter = new NumberFormatter(format);
        decimalFormatter.setValueClass(Double.class);
        decimalFormatter.setMinimum(0.00);
        decimalFormatter.setAllowsInvalid(false);
        
        hoursWork.setFormatterFactory(new DefaultFormatterFactory(decimalFormatter));    
        hoursWork.setValue(0.00);
        
        hoursWork.addPropertyChangeListener("value", evt -> {
            if (hoursWork.getValue() == null)
            {
                hoursWork.setValue(0.00);
            }
        });
    }
    
    // Change the "ratefor_hour_day" field into 0.00 and add the Peso sign. this cannot be change by the user
    private void ratefor()
    {
         Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getCurrencyInstance(localePH);
        decimalFormat.setMinimumFractionDigits(2);
        decimalFormat.setMaximumFractionDigits(2);
       
        NumberFormatter decimalFormatter = new NumberFormatter(decimalFormat);
        decimalFormatter.setAllowsInvalid(false);
        decimalFormatter.setOverwriteMode(false);
        ratefor_hour_day.setFormatterFactory(new DefaultFormatterFactory(decimalFormatter));
        ratefor_hour_day.setValue(0.0);

        ratefor_hour_day.addPropertyChangeListener("value", evt -> 
        {
            if (ratefor_hour_day.getValue() == null)
            {
                ratefor_hour_day.setValue(0.00);
            }
            
        });
    }
    
    // This is where you calcculate grossPay and show the result into texrArea to show to the User
    private void grossPay()
    {
        Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getCurrencyInstance(localePH);
        
        double hour = ((Number) hoursWork.getValue()).doubleValue();
        double rate = ((Number) ratefor_hour_day.getValue()).doubleValue();
        double sum_grossPay = hour * rate;
        data.append(String.valueOf("Gross Pay: " + decimalFormat.getCurrency() + " " + sum_grossPay + "\n")); 
    }
    
    // This is where the Deduction is calculated and show the user what is the deductiion
    private void totalDeduction()
    {
        data.append("Deduction: SSS (5%), Pag-IBIG (2%), PhilHealth (2.5%)" + "\n");
        double total  = 5 + 2.5 + 2;
        data.append("Total Deduction: " + String.valueOf(total) + "%" + "\n");
    }
    
    // This is where the Netpay is Calculated this also show it to the user in the text Area
    private void netPay()
    {
        Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getCurrencyInstance(localePH);
       
       // calculation is done here
        double total  = 5 + 2.5 + 2;
        double hour = ((Number) hoursWork.getValue()).doubleValue();
        double rate = ((Number) ratefor_hour_day.getValue()).doubleValue();
        double sum_grossPay = hour * rate;
        
        double total_netPay = sum_grossPay - (sum_grossPay * total / 100.0);
        
        data.append("Net Pay: " +  decimalFormat.getCurrency() + String.valueOf(total_netPay) + "\n");
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hoursWork = new javax.swing.JFormattedTextField();
        ratefor_hour_day = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Simple Payroll");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Employee Name");

        hoursWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWorkActionPerformed(evt);
            }
        });

        ratefor_hour_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratefor_hour_dayActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hours Worked");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Rate for Hour/Day");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Compute");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        data.setColumns(20);
        data.setRows(5);
        jScrollPane1.setViewportView(data);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hoursWork)
                                .addComponent(ratefor_hour_day)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(8, 8, 8)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratefor_hour_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ratefor_hour_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratefor_hour_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratefor_hour_dayActionPerformed

    private void hoursWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWorkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            
        String studentName = name.getText().trim();
            // Check if the field is emty "isEmpty" will check if the string is empty
            // This check the "name" field if its empty
            if (studentName.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please enter your name.",
                        "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }    
            
            //Check if the "hourWork" field have not entered anything if so warn the user
            Object hours_works = hoursWork.getValue();            
            double check_hour = ((Number) hours_works).doubleValue();

            if (check_hour == 0.0) {
                JOptionPane.showMessageDialog(this, "You forgot to put your hours work" + "\n" + "Please Enter it", "Error", JOptionPane.ERROR_MESSAGE);
                return;
                }
            
            /////////////
            //Check if the "ratefor_hour_day" field have not entered anyting if so warn the user
            Object rate_for_hour_day = ratefor_hour_day.getValue();            
            double check_rate = ((Number) rate_for_hour_day).doubleValue();

            if (check_rate == 0.0) {
                JOptionPane.showMessageDialog(this, "You forgot to put rate" + "\n" + "Please Enter it", "Error", JOptionPane.ERROR_MESSAGE);
                return;
                }
        data.append("" + name.getText() + "\n");
        
        grossPay();
        totalDeduction();
        netPay();
            
        } catch(NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "Wrong Input", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        name.setText(null);
        hoursWork.setValue(null);
        ratefor_hour_day.setValue(null);
        data.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Do you really want to close this window?",
                "Confirm Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        } 
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pt_simplepayrollsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea data;
    private javax.swing.JFormattedTextField hoursWork;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JFormattedTextField ratefor_hour_day;
    // End of variables declaration//GEN-END:variables
}
