/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performanceTasks;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author ihub9
 */
public class pt_simplepayrollsystem extends javax.swing.JFrame {

    /**
     * Creates new form pt_simplepayrollsystem
     */
    public pt_simplepayrollsystem() {
        initComponents();
        hoursWork();
        ratefor();
    }
    private void hoursWork()
    {
         Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getNumberInstance(localePH);
        decimalFormat.setMinimumFractionDigits(2);
        decimalFormat.setMaximumFractionDigits(2);
       
        NumberFormatter decimalFormatter = new NumberFormatter(decimalFormat);
        decimalFormatter.setAllowsInvalid(false);
        decimalFormatter.setOverwriteMode(false);
        hoursWork.setFormatterFactory(new DefaultFormatterFactory(decimalFormatter));
        
        hoursWork.addPropertyChangeListener("value", evt -> 
        {
            if (hoursWork.getValue() == null)
            {
                hoursWork.setValue(0.00);
            }
        });
    }
    
    private void ratefor()
    {
         Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getNumberInstance(localePH);
        decimalFormat.setMinimumFractionDigits(2);
        decimalFormat.setMaximumFractionDigits(2);
       
        NumberFormatter decimalFormatter = new NumberFormatter(decimalFormat);
        decimalFormatter.setAllowsInvalid(false);
        decimalFormatter.setOverwriteMode(false);
        ratefor_hour_day.setFormatterFactory(new DefaultFormatterFactory(decimalFormatter));
        
        ratefor_hour_day.addPropertyChangeListener("value", evt -> 
        {
            if (ratefor_hour_day.getValue() == null)
            {
                ratefor_hour_day.setValue(0.00);
            }
            
        });
    }
    private void grossPay()
    {
        Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getCurrencyInstance(localePH);
        NumberFormatter decimalFormatter = new NumberFormatter(decimalFormat);
        
        double hour = ((Number) hoursWork.getValue()).doubleValue();
        double rate = ((Number) ratefor_hour_day.getValue()).doubleValue();
        data.append(String.valueOf("Gross Pay: " + decimalFormat.getCurrency() + " " + hour * rate + "\n")); 
    }
    private void totalDeduction()
    {
        Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getCurrencyInstance(localePH);
        NumberFormatter decimalFormatter = new NumberFormatter(decimalFormat);
        
        double hour = ((Number) hoursWork.getValue()).doubleValue();
        double rate = ((Number) ratefor_hour_day.getValue()).doubleValue();
        data.append(String.valueOf("Gross Pay: " + decimalFormat.getCurrency() + " " + hour * rate + "\n")); 
    }
    private void netPay()
    {
        Locale localePH = new Locale("en", "PH");
        
        NumberFormat decimalFormat = NumberFormat.getCurrencyInstance(localePH);
        NumberFormatter decimalFormatter = new NumberFormatter(decimalFormat);
        
        double hour = ((Number) hoursWork.getValue()).doubleValue();
        double rate = ((Number) ratefor_hour_day.getValue()).doubleValue();
        data.append(String.valueOf("Gross Pay: " + decimalFormat.getCurrency() + " " + hour * rate + "\n")); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hoursWork = new javax.swing.JFormattedTextField();
        ratefor_hour_day = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("Employee Name");

        hoursWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursWorkActionPerformed(evt);
            }
        });

        ratefor_hour_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratefor_hour_dayActionPerformed(evt);
            }
        });

        jLabel3.setText("Hours Worked");

        jLabel4.setText("Rate for Hour/Day");

        jButton1.setText("Clear");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Quit");

        jLabel6.setText("jLabel6");

        data.setColumns(20);
        data.setRows(5);
        jScrollPane1.setViewportView(data);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hoursWork)
                                .addComponent(ratefor_hour_day)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(8, 8, 8)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratefor_hour_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ratefor_hour_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratefor_hour_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratefor_hour_dayActionPerformed

    private void hoursWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursWorkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        grossPay();               
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pt_simplepayrollsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pt_simplepayrollsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea data;
    private javax.swing.JFormattedTextField hoursWork;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField ratefor_hour_day;
    // End of variables declaration//GEN-END:variables
}
